//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LLCryptoLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LLCryptoLib.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string S00001 {
            get {
                return ResourceManager.GetString("S00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just delete the file without erasing..
        /// </summary>
        internal static string S00002 {
            get {
                return ResourceManager.GetString("S00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete only.
        /// </summary>
        internal static string S00003 {
            get {
                return ResourceManager.GetString("S00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Overwrite.
        /// </summary>
        internal static string S00004 {
            get {
                return ResourceManager.GetString("S00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite the file area with a series of 0 (0x00) bits.
        /// </summary>
        internal static string S00005 {
            get {
                return ResourceManager.GetString("S00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navso P-5329-26.
        /// </summary>
        internal static string S00006 {
            get {
                return ResourceManager.GetString("S00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three times overwrite the file area with a sequence of 0(0x00)-1(0xFF) and a random character.
        /// </summary>
        internal static string S00007 {
            get {
                return ResourceManager.GetString("S00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PseudoRandom.
        /// </summary>
        internal static string S00008 {
            get {
                return ResourceManager.GetString("S00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five times overwrite the file area with a sequence of pseudorandom bits.
        /// </summary>
        internal static string S00009 {
            get {
                return ResourceManager.GetString("S00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoD 5220-22M.
        /// </summary>
        internal static string S00010 {
            get {
                return ResourceManager.GetString("S00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three iterations completely overwrite the file area six times. Each iteration makes two write-passes over the file area: the first pass inscribes ONEs (1) and the next pass inscribes ZEROes (0). After the third iteration, a seventh pass writes the government-designated code “246” across the drive (in hex 0xF6).
        /// </summary>
        internal static string S00011 {
            get {
                return ResourceManager.GetString("S00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutmann.
        /// </summary>
        internal static string S00012 {
            get {
                return ResourceManager.GetString("S00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite the file area 36 times, following the Gutmann standard recommendations..
        /// </summary>
        internal static string S00013 {
            get {
                return ResourceManager.GetString("S00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMG IS5 Enhanced.
        /// </summary>
        internal static string S00014 {
            get {
                return ResourceManager.GetString("S00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three iterations overwrite the file area. The first one inscribes &apos;0&apos;s, the second one &apos;1&apos;s, and finally a random byte is inscribed..
        /// </summary>
        internal static string S00015 {
            get {
                return ResourceManager.GetString("S00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German VSITR.
        /// </summary>
        internal static string S00016 {
            get {
                return ResourceManager.GetString("S00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This 7 passes shred algorithm overwrites the area with 0&apos;s, 1&apos;s, 0&apos;s, 1&apos;s, 0&apos;s, 1&apos;s and finally &apos;A&apos; byte (0x41).
        /// </summary>
        internal static string S00017 {
            get {
                return ResourceManager.GetString("S00017", resourceCulture);
            }
        }
    }
}
