//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckForUpdatesWPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckForUpdatesWPF.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection with http://www.littlelite.net ....
        /// </summary>
        internal static string S00001 {
            get {
                return ResourceManager.GetString("S00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find version information for.
        /// </summary>
        internal static string S00002 {
            get {
                return ResourceManager.GetString("S00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: v.
        /// </summary>
        internal static string S00003 {
            get {
                return ResourceManager.GetString("S00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Press &quot;Download&quot; to update..
        /// </summary>
        internal static string S00004 {
            get {
                return ResourceManager.GetString("S00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download....
        /// </summary>
        internal static string S00005 {
            get {
                return ResourceManager.GetString("S00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string S00006 {
            get {
                return ResourceManager.GetString("S00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest available version..
        /// </summary>
        internal static string S00007 {
            get {
                return ResourceManager.GetString("S00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string S00008 {
            get {
                return ResourceManager.GetString("S00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        internal static string S00009 {
            get {
                return ResourceManager.GetString("S00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the most current version.
        /// </summary>
        internal static string S00010 {
            get {
                return ResourceManager.GetString("S00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new version....
        /// </summary>
        internal static string S00011 {
            get {
                return ResourceManager.GetString("S00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install new version, just run downloaded file..
        /// </summary>
        internal static string S00012 {
            get {
                return ResourceManager.GetString("S00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL must start with &apos;http://&apos;.
        /// </summary>
        internal static string S00013 {
            get {
                return ResourceManager.GetString("S00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port must be an integer.
        /// </summary>
        internal static string S00014 {
            get {
                return ResourceManager.GetString("S00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string S00015 {
            get {
                return ResourceManager.GetString("S00015", resourceCulture);
            }
        }
    }
}
