//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteErrorReportWPF.net.littlelite.www {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.littlelite.net/webservices", ConfigurationName="net.littlelite.www.ProgramFeedbackSoap")]
    public interface ProgramFeedbackSoap {
        
        // CODEGEN: Generating message contract since element name program from namespace http://www.littlelite.net/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.littlelite.net/webservices/SendFeedback", ReplyAction="*")]
        LiteErrorReportWPF.net.littlelite.www.SendFeedbackResponse SendFeedback(LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFeedbackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFeedback", Namespace="http://www.littlelite.net/webservices", Order=0)]
        public LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequestBody Body;
        
        public SendFeedbackRequest() {
        }
        
        public SendFeedbackRequest(LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.littlelite.net/webservices")]
    public partial class SendFeedbackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string feedback;
        
        public SendFeedbackRequestBody() {
        }
        
        public SendFeedbackRequestBody(string program, string feedback) {
            this.program = program;
            this.feedback = feedback;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFeedbackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFeedbackResponse", Namespace="http://www.littlelite.net/webservices", Order=0)]
        public LiteErrorReportWPF.net.littlelite.www.SendFeedbackResponseBody Body;
        
        public SendFeedbackResponse() {
        }
        
        public SendFeedbackResponse(LiteErrorReportWPF.net.littlelite.www.SendFeedbackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.littlelite.net/webservices")]
    public partial class SendFeedbackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFeedbackResult;
        
        public SendFeedbackResponseBody() {
        }
        
        public SendFeedbackResponseBody(string SendFeedbackResult) {
            this.SendFeedbackResult = SendFeedbackResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProgramFeedbackSoapChannel : LiteErrorReportWPF.net.littlelite.www.ProgramFeedbackSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramFeedbackSoapClient : System.ServiceModel.ClientBase<LiteErrorReportWPF.net.littlelite.www.ProgramFeedbackSoap>, LiteErrorReportWPF.net.littlelite.www.ProgramFeedbackSoap {
        
        public ProgramFeedbackSoapClient() {
        }
        
        public ProgramFeedbackSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramFeedbackSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramFeedbackSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramFeedbackSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiteErrorReportWPF.net.littlelite.www.SendFeedbackResponse LiteErrorReportWPF.net.littlelite.www.ProgramFeedbackSoap.SendFeedback(LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequest request) {
            return base.Channel.SendFeedback(request);
        }
        
        public string SendFeedback(string program, string feedback) {
            LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequest inValue = new LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequest();
            inValue.Body = new LiteErrorReportWPF.net.littlelite.www.SendFeedbackRequestBody();
            inValue.Body.program = program;
            inValue.Body.feedback = feedback;
            LiteErrorReportWPF.net.littlelite.www.SendFeedbackResponse retVal = ((LiteErrorReportWPF.net.littlelite.www.ProgramFeedbackSoap)(this)).SendFeedback(inValue);
            return retVal.Body.SendFeedbackResult;
        }
    }
}
